# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/settings.ui'
#
# Created: Mon Jan 12 18:11:07 2015
#      by: PyQt4 UI code generator 4.10.4-snapshot-595c1453ae29
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_settingsDialog(object):
    def setupUi(self, settingsDialog):
        settingsDialog.setObjectName(_fromUtf8("settingsDialog"))
        settingsDialog.resize(437, 380)
        self.verticalLayout = QtGui.QVBoxLayout(settingsDialog)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabWidget = QtGui.QTabWidget(settingsDialog)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.gridLayout_3 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.groupBox_2 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_2.setMaximumSize(QtCore.QSize(16777215, 100))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.scalebarSB = QtGui.QSpinBox(self.groupBox_2)
        self.scalebarSB.setMaximum(9999)
        self.scalebarSB.setProperty("value", 10)
        self.scalebarSB.setObjectName(_fromUtf8("scalebarSB"))
        self.gridLayout_4.addWidget(self.scalebarSB, 1, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.groupBox_2)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_4.addWidget(self.label_8, 1, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_2, 1, 0, 1, 1)
        self.groupBox = QtGui.QGroupBox(self.tab_2)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_5.addWidget(self.label_6, 1, 0, 1, 1)
        self.condatisEdit = QtGui.QLineEdit(self.groupBox)
        self.condatisEdit.setReadOnly(False)
        self.condatisEdit.setObjectName(_fromUtf8("condatisEdit"))
        self.gridLayout_5.addWidget(self.condatisEdit, 1, 1, 1, 1)
        self.pushButton_2 = QtGui.QPushButton(self.groupBox)
        self.pushButton_2.setEnabled(True)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.gridLayout_5.addWidget(self.pushButton_2, 1, 2, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_5.addWidget(self.label_5, 2, 0, 1, 1)
        self.manualEdit = QtGui.QLineEdit(self.groupBox)
        self.manualEdit.setReadOnly(False)
        self.manualEdit.setObjectName(_fromUtf8("manualEdit"))
        self.gridLayout_5.addWidget(self.manualEdit, 2, 1, 1, 1)
        self.pushButton = QtGui.QPushButton(self.groupBox)
        self.pushButton.setEnabled(True)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.gridLayout_5.addWidget(self.pushButton, 2, 2, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayout = QtGui.QGridLayout(self.tab)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.cbar = MplWidget(self.tab)
        self.cbar.setMinimumSize(QtCore.QSize(0, 25))
        self.cbar.setMaximumSize(QtCore.QSize(16777215, 100))
        self.cbar.setObjectName(_fromUtf8("cbar"))
        self.gridLayout.addWidget(self.cbar, 1, 0, 1, 1)
        self.frame = QtGui.QFrame(self.tab)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.gridLayout_2 = QtGui.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label = QtGui.QLabel(self.frame)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_2.addWidget(self.label, 3, 0, 1, 1)
        self.voltageReverse = QtGui.QCheckBox(self.frame)
        self.voltageReverse.setText(_fromUtf8(""))
        self.voltageReverse.setObjectName(_fromUtf8("voltageReverse"))
        self.gridLayout_2.addWidget(self.voltageReverse, 7, 2, 1, 1)
        self.flowComboBox = QtGui.QComboBox(self.frame)
        self.flowComboBox.setObjectName(_fromUtf8("flowComboBox"))
        self.gridLayout_2.addWidget(self.flowComboBox, 4, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.frame)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 4, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.frame)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 7, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.frame)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_2.addWidget(self.label_7, 0, 2, 1, 1)
        self.flowReverse = QtGui.QCheckBox(self.frame)
        self.flowReverse.setMaximumSize(QtCore.QSize(20, 16777215))
        self.flowReverse.setText(_fromUtf8(""))
        self.flowReverse.setObjectName(_fromUtf8("flowReverse"))
        self.gridLayout_2.addWidget(self.flowReverse, 4, 2, 1, 1)
        self.powerReverse = QtGui.QCheckBox(self.frame)
        self.powerReverse.setText(_fromUtf8(""))
        self.powerReverse.setObjectName(_fromUtf8("powerReverse"))
        self.gridLayout_2.addWidget(self.powerReverse, 6, 2, 1, 1)
        self.powerComboBox = QtGui.QComboBox(self.frame)
        self.powerComboBox.setObjectName(_fromUtf8("powerComboBox"))
        self.gridLayout_2.addWidget(self.powerComboBox, 6, 1, 1, 1)
        self.voltageComboBox = QtGui.QComboBox(self.frame)
        self.voltageComboBox.setObjectName(_fromUtf8("voltageComboBox"))
        self.gridLayout_2.addWidget(self.voltageComboBox, 7, 1, 1, 1)
        self.habReverse = QtGui.QCheckBox(self.frame)
        self.habReverse.setText(_fromUtf8(""))
        self.habReverse.setObjectName(_fromUtf8("habReverse"))
        self.gridLayout_2.addWidget(self.habReverse, 3, 2, 1, 1)
        self.habComboBox = QtGui.QComboBox(self.frame)
        self.habComboBox.setObjectName(_fromUtf8("habComboBox"))
        self.gridLayout_2.addWidget(self.habComboBox, 3, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.frame)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 6, 0, 1, 1)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        self.buttonBox = QtGui.QDialogButtonBox(settingsDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(settingsDialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), settingsDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), settingsDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(settingsDialog)

    def retranslateUi(self, settingsDialog):
        settingsDialog.setWindowTitle(_translate("settingsDialog", "Settings", None))
        self.groupBox_2.setTitle(_translate("settingsDialog", "Settings", None))
        self.label_8.setText(_translate("settingsDialog", "Scale bar length (km)", None))
        self.groupBox.setTitle(_translate("settingsDialog", "Paths", None))
        self.label_6.setText(_translate("settingsDialog", "Condatis Home", None))
        self.condatisEdit.setToolTip(_translate("settingsDialog", "Not implemented", None))
        self.condatisEdit.setText(_translate("settingsDialog", "maps", None))
        self.pushButton_2.setText(_translate("settingsDialog", "Find", None))
        self.label_5.setText(_translate("settingsDialog", "Manual", None))
        self.manualEdit.setToolTip(_translate("settingsDialog", "Not yet implemented", None))
        self.manualEdit.setText(_translate("settingsDialog", "doc/manual", None))
        self.pushButton.setText(_translate("settingsDialog", "Find", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("settingsDialog", "General", None))
        self.label.setText(_translate("settingsDialog", "Habitat map", None))
        self.label_3.setText(_translate("settingsDialog", "Flow map", None))
        self.label_2.setText(_translate("settingsDialog", "Progress map", None))
        self.label_7.setText(_translate("settingsDialog", "Reverse", None))
        self.label_4.setText(_translate("settingsDialog", "Bottlenecks map", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("settingsDialog", "Colour Maps", None))

from mplwidget import MplWidget

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    settingsDialog = QtGui.QDialog()
    ui = Ui_settingsDialog()
    ui.setupUi(settingsDialog)
    settingsDialog.show()
    sys.exit(app.exec_())

