# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/sourcesinkui2.ui'
#
# Created: Mon Jan 12 18:11:06 2015
#      by: PyQt4 UI code generator 4.10.4-snapshot-595c1453ae29
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_SourceSinkDialog(object):
    def setupUi(self, SourceSinkDialog):
        SourceSinkDialog.setObjectName(_fromUtf8("SourceSinkDialog"))
        SourceSinkDialog.resize(429, 302)
        self.verticalLayout = QtGui.QVBoxLayout(SourceSinkDialog)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabWidget = QtGui.QTabWidget(SourceSinkDialog)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.frame_3 = QtGui.QFrame(self.tab)
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.gridLayout = QtGui.QGridLayout(self.frame_3)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.sourceText = QtGui.QLineEdit(self.frame_3)
        self.sourceText.setObjectName(_fromUtf8("sourceText"))
        self.gridLayout.addWidget(self.sourceText, 1, 2, 1, 1)
        self.sourcePb = QtGui.QPushButton(self.frame_3)
        self.sourcePb.setObjectName(_fromUtf8("sourcePb"))
        self.gridLayout.addWidget(self.sourcePb, 1, 3, 1, 1)
        self.srcValSpinBox = QtGui.QSpinBox(self.frame_3)
        self.srcValSpinBox.setProperty("value", 1)
        self.srcValSpinBox.setObjectName(_fromUtf8("srcValSpinBox"))
        self.gridLayout.addWidget(self.srcValSpinBox, 2, 3, 1, 1)
        self.label_4 = QtGui.QLabel(self.frame_3)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.frame_3)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 3, 2, 1, 1)
        self.label_2 = QtGui.QLabel(self.frame_3)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 2, 2, 1, 1)
        self.snkValSpinBox = QtGui.QSpinBox(self.frame_3)
        self.snkValSpinBox.setProperty("value", 2)
        self.snkValSpinBox.setObjectName(_fromUtf8("snkValSpinBox"))
        self.gridLayout.addWidget(self.snkValSpinBox, 3, 3, 1, 1)
        self.verticalLayout_5.addWidget(self.frame_3)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.tab_2)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.groupBox = QtGui.QGroupBox(self.tab_2)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.radioButton_2 = QtGui.QRadioButton(self.groupBox)
        self.radioButton_2.setChecked(True)
        self.radioButton_2.setObjectName(_fromUtf8("radioButton_2"))
        self.verticalLayout_3.addWidget(self.radioButton_2)
        self.radioButton = QtGui.QRadioButton(self.groupBox)
        self.radioButton.setObjectName(_fromUtf8("radioButton"))
        self.verticalLayout_3.addWidget(self.radioButton)
        self.radioButton_3 = QtGui.QRadioButton(self.groupBox)
        self.radioButton_3.setObjectName(_fromUtf8("radioButton_3"))
        self.verticalLayout_3.addWidget(self.radioButton_3)
        self.radioButton_4 = QtGui.QRadioButton(self.groupBox)
        self.radioButton_4.setObjectName(_fromUtf8("radioButton_4"))
        self.verticalLayout_3.addWidget(self.radioButton_4)
        self.horizontalLayout.addWidget(self.groupBox)
        self.frame = QtGui.QFrame(self.tab_2)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.checkBox_2 = QtGui.QCheckBox(self.frame)
        self.checkBox_2.setChecked(True)
        self.checkBox_2.setObjectName(_fromUtf8("checkBox_2"))
        self.verticalLayout_4.addWidget(self.checkBox_2)
        self.frame_2 = QtGui.QFrame(self.frame)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label = QtGui.QLabel(self.frame_2)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_2.addWidget(self.label)
        self.spinBox_2 = QtGui.QSpinBox(self.frame_2)
        self.spinBox_2.setProperty("value", 3)
        self.spinBox_2.setObjectName(_fromUtf8("spinBox_2"))
        self.horizontalLayout_2.addWidget(self.spinBox_2)
        self.verticalLayout_4.addWidget(self.frame_2)
        self.horizontalLayout.addWidget(self.frame)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.tab_3)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.groupBox_2 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.clearSourceRB = QtGui.QRadioButton(self.groupBox_2)
        self.clearSourceRB.setChecked(False)
        self.clearSourceRB.setObjectName(_fromUtf8("clearSourceRB"))
        self.verticalLayout_2.addWidget(self.clearSourceRB)
        self.clearTargetRB = QtGui.QRadioButton(self.groupBox_2)
        self.clearTargetRB.setObjectName(_fromUtf8("clearTargetRB"))
        self.verticalLayout_2.addWidget(self.clearTargetRB)
        self.clearBothRB = QtGui.QRadioButton(self.groupBox_2)
        self.clearBothRB.setChecked(True)
        self.clearBothRB.setObjectName(_fromUtf8("clearBothRB"))
        self.verticalLayout_2.addWidget(self.clearBothRB)
        self.horizontalLayout_3.addWidget(self.groupBox_2)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        self.buttonBox = QtGui.QDialogButtonBox(SourceSinkDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(SourceSinkDialog)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), SourceSinkDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), SourceSinkDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(SourceSinkDialog)

    def retranslateUi(self, SourceSinkDialog):
        SourceSinkDialog.setWindowTitle(_translate("SourceSinkDialog", "Assign Source and Target", None))
        self.sourceText.setText(_translate("SourceSinkDialog", "maps/sourcesink.tif", None))
        self.sourcePb.setText(_translate("SourceSinkDialog", "Find", None))
        self.label_4.setText(_translate("SourceSinkDialog", "Source", None))
        self.label_3.setText(_translate("SourceSinkDialog", "Target Value", None))
        self.label_2.setText(_translate("SourceSinkDialog", "Source Value", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("SourceSinkDialog", "From File", None))
        self.groupBox.setTitle(_translate("SourceSinkDialog", "Generate source and sink:", None))
        self.radioButton_2.setText(_translate("SourceSinkDialog", "North to South", None))
        self.radioButton.setText(_translate("SourceSinkDialog", "South to North", None))
        self.radioButton_3.setText(_translate("SourceSinkDialog", "West to East", None))
        self.radioButton_4.setText(_translate("SourceSinkDialog", "East to West", None))
        self.checkBox_2.setText(_translate("SourceSinkDialog", "Expand Area", None))
        self.label.setText(_translate("SourceSinkDialog", "Width", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("SourceSinkDialog", "Auto", None))
        self.groupBox_2.setTitle(_translate("SourceSinkDialog", "Clear Source and Target", None))
        self.clearSourceRB.setText(_translate("SourceSinkDialog", "Clear source", None))
        self.clearTargetRB.setText(_translate("SourceSinkDialog", "Clear target", None))
        self.clearBothRB.setText(_translate("SourceSinkDialog", "Clear both source and target", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("SourceSinkDialog", "Clear", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    SourceSinkDialog = QtGui.QDialog()
    ui = Ui_SourceSinkDialog()
    ui.setupUi(SourceSinkDialog)
    SourceSinkDialog.show()
    sys.exit(app.exec_())

